### ISSUE TITLE
Android: NullPointerException on app start

### ISSUE THREAD

**Issue by Hranatikk** [appodeal/react-native-appodeal#118]
Hi,

On first app launch on Android it always crash
Logs: 

```
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method com.appodeal.ads.Appodeal.initialize, parameter context
       at com.appodeal.ads.Appodeal.initialize(:2)
       at com.appodeal.rnappodeal.RNAppodealModule.initializeWithAppKey(RNAppodealModule.java:75)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:255)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:923)
```

       
  What I call on app initialization
```
const adTypes = AppodealAdType.REWARDED_VIDEO
Appodeal.setTesting(true)
Appodeal.initialize("myAppKey", adTypes)
```

All steps from Android installation section was done

**Comment by elwadi** [comment]
#112

**Comment by da2gl** [comment]
https://github.com/appodeal/react-native-appodeal/pull/131
