### ISSUE TITLE
sendEventToJS() crashes on Android

### ISSUE THREAD

**Issue by 90minutes** [appodeal/react-native-appodeal#82]
Hi there!

First of all, thanks for the amazing work. Been using this for months in production. But there has been this issue since I first added Appodeal:

```
Fatal Exception: java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
       at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:148)
       at com.appodeal.rnappodeal.RNAppodealModule.sendEventToJS(RNAppodealModule.java:61)
       at com.appodeal.rnappodeal.RNAppodealModule.onInterstitialFailedToLoad(RNAppodealModule.java:460)
       at com.appodeal.ads.ap$a.a(:48)
       at com.appodeal.ads.an$a$1.run(:7)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7266)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Would you please help with that?

**Comment by staskochkin** [comment]
Hello @90minutes, this [commit](https://github.com/appodeal/react-native-appodeal/commit/5a0c85149943c2e7c65d528048c74e73543b5fa9) should fix this issue

**Comment by 90minutes** [comment]
Thank you!

**Comment by 90minutes** [comment]
@staskochkin, can you please publish the changes on npm? Thanks!

**Comment by staskochkin** [comment]
@90minutes Changes has been added into [2.10.2 release](https://www.npmjs.com/package/react-native-appodeal/v/2.10.2).
